config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments do
    	resources :replies
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	#belongs_to :user
	belongs_to :post
	has_many :replies, dependent: :destroy
	has_many :likes, as: :likeable
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
	#belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, as: :likeable
    validates :title, presence: true	
end

app/models/reply.rb
class Reply < ApplicationRecord
	belongs_to :comment
	#belongs_to :user
	has_many :likes, as: :likeable
end

app/models/user.rb
class User < ApplicationRecord
	#has_many :posts
	#has_many :comments
	#has_many :likes
	#has_many :replies
	#has_many :comment_posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		
	end

	def show
		
	end

	def new
		
	end

	def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
      redirect_to post_path(@post)
    end
   
   
   def edit
   	@post = Post.find(params[:post_id])
   	@comment = @post.comments.find(params[:id])
   end

   def update
   	 @post = Post.find(params[:post_id])
   	 @comment = @post.comments.find(params[:id])
   	 if @comment.update(comment_params)
   	 	redirect_to post_path(@post)
   	 else
   	 	render 'edit'
   	 end
   end
   
   def destroy
   	 @post = Post.find(params[:post_id])
     @comment = @post.comments.find(params[:id])
     @comment.destroy
     redirect_to post_path(@post)
   end
   	
   
  private
    def comment_params
      params.require(:comment).permit(:title)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
 
  def show
    @post = Post.find(params[:id])
  end
 
  def new
    @post = Post.new
  end
 
  def edit
    @post = Post.find(params[:id])
  end
 
  def create
    @post = Post.new(post_params)
 
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
 
  def update
    @post = Post.find(params[:id])
 
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
 
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
 
    redirect_to posts_path
  end
 
  private
    def post_params
      params.require(:post).permit(:title)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	def new
		@reply = Reply.new
	end
	def create
		#debugger
		#@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:comment_id])
		@reply = @comment.replies.new(reply_params)
		if @reply.save
			redirect_to post_path(@comment.post, @comment)
		else
			render 'new'
		end
	end

	def edit
   	@post = Post.find(params[:post_id])
   	@comment = @post.comments.find(params[:comment_id])
   	@reply = @comment.replies.find(params[:id])
   end

   def update
   	debugger
   	 @post = Post.find(params[:post_id])
   	 @comment = @post.comments.find(params[:comment_id])
   	 @reply = @comment.replies.find(params[:id])
   	 if @reply.update(reply_params)
   	 	redirect_to post_path(@reply.comment.post)
   	 else
   	 	render 'edit'
   	 end
   end

    def destroy
    	@reply = Replay.find(params[:id])
    	if @reply.destroy
          redirect_to post_path(@reply.comment.post)
      else
      	  render 'posts/show'
      end
    end

	private
    def reply_params
      params.require(:reply).permit(:reply_on_comment)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pclr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', post_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<%= link_to 'New post', new_post_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 <hr>

 <h3>total comments :<%= @post.comments.count%></h3>
 <hr>
<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.title %>
     <%= link_to ' delete comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>||
    <%= link_to ' edit comment', edit_post_comment_path(comment.post, comment), data: { confirm: 'Are you sure what to edit?' } %>
   <%= link_to ' reply on comment',  new_post_comment_reply_path(comment.post, comment) %>
    <hr>
    <h3>total replies:<%=comment.replies.count%> </h3>

    <%comment.replies.each do |reply|%>
    
    <h4>reply:<%=reply.reply_on_comment%></h4>
    <%= link_to ' delete reply', post_comment_reply_path(reply.comment.post, reply.comment, reply), method: :delete, data: { confirm: 'Are you sure?' } %>||
  <%= link_to ' edit reply', edit_post_comment_reply_path(reply.comment.post,reply.comment, reply), data: { confirm: 'Are you sure what to edit?' } %>
    <%end%>
  </p>

  
  
<% end %>
 
<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/replies/edit.html.erb
<%= form_for([@post, @comment, @reply]) do |f| %>
 
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reply.errors.count, "error") %> prohibited
        this reply from being saved:
      </h2>
      <ul>
        <% @reply.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :reply_on_comment %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/replies/new.html.erb
<%= form_for :reply, url: post_comment_replies_path do |f| %>
 
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reply.errors.count, "error") %> prohibited
        this reply from being saved:
      </h2>
      <ul>
        <% @reply.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :reply_on_comment %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>